site_name: "Cours Big Data"
site_description: "TP Hadoop avec Docker"
nav:
  - Accueil: index.md
  - Démarrage: deployment.md
  - Explorer HDFS: hdfs.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
theme:
  name: readthedocs
extra_css:
  - css/custom.css
extra:
  generator: false

copyright: © 2026 Ton Nom / Ton Cours - Tous droits réservés
